export const allProducts = [
  // ABAYAS (8 images)
  ...[1, 2, 3, 4, 5, 6, 7, 8].map(i => ({
    _id: `a${i}`,
    name: `Premium Abaya Luxury Collection Vol. ${i}`,
    price: 6000 + i * 500,
    discountPrice: 4000 + i * 300,
    rating: (4.5 + (i % 5) / 10).toFixed(1),
    reviewCount: 15 + i * 3,
    category: 'Abaya',
    stock: 10 + i,
    sku: `NE-AB-00${i}`,
    colors: ['Emerald', 'Midnight Black', 'Desert Sand'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [`abaya/abaya${i}.jpg`, `abaya/abaya${(i % 8) + 1}.jpg`],
    description: `Exquisite Abaya from our Noor-e-Eman Boutique Series. Crafted from high-grade fabric with precision tailoring. This design offers perfect modesty without compromising on modern luxury. Breathable material suitable for all seasons.`,
    features: ['Premium Modest Cut', 'Wrinkle-Resistant Fabric', 'Hand-finished Detail'],
    specifications: { Material: 'Nidha / Crepe Blend', Origin: 'Boutique Crafted' },
    care: 'Professional Dry Clean recommended. Hand wash cold if necessary.'
  })),

  // JUBBAS (6 images)
  ...[1, 2, 3, 4, 5, 6].map(i => ({
    _id: `j${i}`,
    name: `Royal Heritage Jubba Style ${i}`,
    price: 5000 + i * 400,
    discountPrice: 3500 + i * 200,
    rating: (4.7 + (i % 3) / 10).toFixed(1),
    reviewCount: 25 + i * 5,
    category: 'Jubba',
    stock: 12 + i,
    sku: `NE-JB-00${i}`,
    colors: ['Pure White', 'Slate', 'Royal Navy'],
    sizes: ['52', '54', '56', '58', '60'],
    images: [`jubba/jubba${i}.jpg`, `jubba/jubba${(i % 6) + 1}.jpg`],
    description: `A masterpiece of traditional menswear. This Jubba combines centuries-old styles with contemporary tailoring. Perfect for Jummah, Eid, or formal gatherings. Made from sweat-wicking premium fabric.`,
    features: ['Authentic Arabic Cut', 'Hidden Stitching', 'Mobile Friendly Pockets'],
    specifications: { Material: 'Spun Polyester', Style: 'Emirati/Saudi' },
    care: 'Machine wash warm. Steam iron for a crisp finish.'
  })),

  // TOPI / PRAYER CAPS (4 images)
  {
    _id: 'c1',
    name: 'Classic Cotton Prayer Cap',
    price: 450,
    discountPrice: 250,
    rating: '4.9',
    reviewCount: 150,
    category: 'Topi',
    stock: 100,
    sku: 'NE-TP-001',
    images: ['PrayerCap/cap1.jpg'],
    description: 'Breathable, stretchable, and perfectly comfortable for daily use.',
    features: ['100% Cotton', 'One size fits all'],
    specifications: { Material: 'Cotton', Origin: 'Hand-knitted' },
    care: 'Hand wash cold.'
  },
  {
    _id: 'c2',
    name: 'Luxury Velvet Sultan Topi',
    price: 1200,
    discountPrice: 850,
    rating: '5.0',
    reviewCount: 45,
    category: 'Topi',
    stock: 30,
    sku: 'NE-TP-002',
    images: ['PrayerCap/topi2.jpg'],
    description: 'Premium velvet with gold-thread accents for special occasions.',
    features: ['Ultra-soft Velvet', 'Gold Accents'],
    specifications: { Material: 'Velvet', Finish: 'Glossy' },
    care: 'Dry clean only.'
  },
  {
    _id: 'c3',
    name: 'Traditional Sufi Knit Cap',
    price: 800,
    discountPrice: 550,
    rating: '4.8',
    reviewCount: 62,
    category: 'Topi',
    stock: 40,
    sku: 'NE-TP-003',
    images: ['PrayerCap/topi3.jpg'],
    description: 'Traditional thick-knit cap providing a sturdy and dignified look.',
    features: ['Hand-made Texture', 'Durable Yarn'],
    specifications: { Material: 'Wool Blend', Origin: 'Local' },
    care: 'Hand wash only.'
  },
  {
    _id: 'c4',
    name: 'Moroccan Designer Thobe Cap',
    price: 1800,
    discountPrice: 1200,
    rating: '5.0',
    reviewCount: 22,
    category: 'Topi',
    stock: 15,
    sku: 'NE-TP-004',
    images: ['PrayerCap/topi4.com___[Morocoon Thobes, Adult Thobes, Thobes, Premium Quality, Fashion, Affordable Sunnah, Topiwala, Topiwala Clothing]'],
    description: 'High-end Moroccan style embroidered cap. A true designer piece.',
    features: ['Silk Embroidery', 'Firm Structure'],
    specifications: { Style: 'Moroccan', Material: 'Premium Cotton' },
    care: 'Spot clean only.'
  },

  // JAINAMAZ (8 images)
  ...[1, 2, 3, 4, 5, 6, 7, 8].map(i => ({
    _id: `m${i}`,
    name: `Luxury Plush Jainamaz Series ${i}`,
    price: 4500 + i * 200,
    discountPrice: 2800 + i * 150,
    rating: '4.9',
    reviewCount: 30 + i,
    category: 'Jainamaz',
    stock: 20,
    sku: `NE-JM-00${i}`,
    images: [`jainamaz/jainamaz${i}.jpg`],
    description: 'A sanctuary for your soul. This plush velvet prayer mat provides unmatched comfort during your daily prayers.',
    features: ['High-density Foam', 'Anti-slip base', 'Traditional Mihrab pattern'],
    specifications: { Material: 'Premium Velvet', Padding: '10mm' },
    care: 'Vacuum clean regularly. Spot clean with mild soap.'
  })),

  // TASBIH (8 images)
  ...[1, 2, 3, 4, 5, 6, 7, 8].map(i => ({
    _id: `t${i}`,
    name: `Spiritual Reflection Tasbih ${i}`,
    price: 1500 + i * 100,
    discountPrice: 900 + i * 50,
    rating: '5.0',
    reviewCount: 40 + i,
    category: 'Tasbih',
    stock: 50,
    sku: `NE-TS-00${i}`,
    images: [`tasbih/tasbih${i}.jpg`],
    description: 'Hand-strung prayer beads designed to assist in your daily dhikr with tranquility.',
    features: ['99 High-quality beads', 'Silk Tassel', 'Sturdy cord'],
    specifications: { Material: 'Crystal / Gemstone', Count: '99' },
    care: 'Keep in provided pouch when not in use.'
  })),

  // BOOKS (6 images)
  ...[1, 2, 3, 4, 5, 6].map(i => ({
    _id: `b${i}`,
    name: `Divine Knowledge Book Vol. ${i}`,
    price: 2500 + i * 300,
    discountPrice: 1500 + i * 100,
    rating: '5.0',
    reviewCount: 15 + i,
    category: 'Books',
    stock: 5,
    sku: `NE-BK-00${i}`,
    images: [`books/book${i}.jpg`],
    description: 'A valuable addition to your Islamic library. Essential reading for every Muslim seeker of knowledge.',
    features: ['High-quality Paper', 'Golden Embossing', 'Clear Typography'],
    specifications: { Genre: 'Islamic Studies', Binding: 'Hardcover' },
    care: 'Keep in a dry, shaded area.'
  })),

  // FRAGRANCES (4 images)
  {
    _id: 'f1',
    name: 'Royal Oud Signature Attar',
    price: 4500,
    discountPrice: 2500,
    rating: '5.0',
    reviewCount: 88,
    category: 'Fragrances',
    stock: 20,
    sku: 'NE-FR-001',
    images: ['Fragrances1.jpg'],
    description: 'Deep, woody, and captivating. Our signature non-alcoholic Oud.',
    features: ['100% Non-alcoholic', '8-12 hour lasting'],
    specifications: { Base: 'Pure Oud', Notes: 'Spicy/Woody' },
    care: 'Keep away from heat.'
  },
  ...[2, 3, 4].map(i => ({
    _id: `f${i}`,
    name: `Premium Spiritual Scent ${i}`,
    price: 3500 + i * 200,
    discountPrice: 1800 + i * 150,
    rating: '4.9',
    reviewCount: 20 + i,
    category: 'Fragrances',
    stock: 15,
    sku: `NE-FR-00${i}`,
    images: [`fragrances/fragrances${i}.jpg`],
    description: 'Concentrated perfume oil that uplifts the spirit and lasts throughout the day.',
    features: ['Premium Quality Oil', 'Travel size bottle'],
    specifications: { Volume: '12ml', Type: 'Attar' },
    care: 'Store upright.'
  }))
];
